In [1]:
import pandas as pd

In [2]:
data = {
    "id": [101, 102, 103, 104, 105, 106],
    "age": [24, 31, 27, 19, 42, 35],
    "group": ["A", "B", "A", "B", "A", "B"],
    "score": [81, 94, 88, 72, 91, 85]
}

df = pd.DataFrame(data)

In [15]:
#df
#df.head()
df.shape
#df.columns
#df.index
#df.dtypes
#df.info()
#df.describe()

(6, 4)

How many observations are there?
-> There are six observations
How many variables?
-> There are 4 variables
Which columns are numeric?
-> ID, Age, and Score
What is the default index?
-> (0,6)
What does df.shape return?
-> This returns the dimension of our matrix of data. It returns (6,4), which means we have 6 rows and 4 columns. 

In [24]:
age = df["age"]
print(age)
type(age)

0    24
1    31
2    27
3    19
4    42
5    35
Name: age, dtype: int64


pandas.Series

In [21]:
age_df = df[["age"]]
print(age_df)
type(age_df)

   age
0   24
1   31
2   27
3   19
4   42
5   35


pandas.DataFrame

By nesting age as a list in the second code block we make it so that we can reference the entire table as it references to age. Not having it as a list will just return the column of ages with no context. 
Series add element-by-element down the rows
Dataframes add elelement-by-element across the columns

In [25]:
df["score"]

0    81
1    94
2    88
3    72
4    91
5    85
Name: score, dtype: int64

In [26]:
df[["age", "score"]]

,age,score
0,24,81
1,31,94
2,27,88
3,19,72
4,42,91
5,35,85


In [30]:
analysis_df = df.drop(columns=["age"])
print(analysis_df)

    id group  score
0  101     A     81
1  102     B     94
2  103     A     88
3  104     B     72
4  105     A     91
5  106     B     85


In [31]:
df.iloc[0]

id       101
age       24
group      A
score     81
Name: 0, dtype: object

In [32]:
df.iloc[0:3]

,id,age,group,score
0,101,24,A,81
1,102,31,B,94
2,103,27,A,88


In [33]:
df.iloc[[0, 2, 5]]

,id,age,group,score
0,101,24,A,81
2,103,27,A,88
5,106,35,B,85


In [34]:
df.iloc[1:4, 1:3]

,age,group
1,31,B
2,27,A
3,19,B


1.) the first argument selects row
2.) the second argument selects the column
3.) No it is not, it is excluded. 

In [35]:
df = df.set_index("id")

In [36]:
df
df.index

RangeIndex(start=101, stop=107, step=1, name='id')

In [ ]:
df.loc[101]


age      24
group     A
score    81
Name: 101, dtype: object

In [38]:
df.iloc[0]

age      24
group     A
score    81
Name: 101, dtype: object

.loc is refereing to the 'id' of 101, and .iloc is refering to the 0th row in the dataset, which correspons to where 'id'=101 

In [42]:
df.loc[101]

age      24
group     A
score    81
Name: 101, dtype: object

In [41]:
df.loc[[101,103,105]]

,age,group,score
id,,,
101,24,A,81
103,27,A,88
105,42,A,91


In [46]:
df.loc[[102,104,106]].values

array([[31, 'B', 94],
       [19, 'B', 72],
       [35, 'B', 85]], dtype=object)

In [47]:
small = pd.DataFrame(
    {"value": [10, 20, 30, 40]},
    index=[101, 205, 310, 412]
)

In [48]:
small.loc[205]

value    20
Name: 205, dtype: int64

In [49]:
small.iloc[1]

value    20
Name: 205, dtype: int64

.loc uses the name in the dataframe, .iloc uses the position of the information we want within the dataframe.

In [50]:
df.iloc[1:4]

,age,group,score
id,,,
102,31,B,94
103,27,A,88
104,19,B,72


In [51]:
df.loc[102:105]

,age,group,score
id,,,
102,31,B,94
103,27,A,88
104,19,B,72
105,42,A,91


Label based splicing includes the end value, whereas positinal does not. 

Part 9

In [52]:
df.loc[:, ["age", "score"]]

,age,score
id,,
101,24,81
102,31,94
103,27,88
104,19,72
105,42,91
106,35,85


In [53]:
df.loc[
    102:105,
    ["age", "score"]
]

,age,score
id,,
102,31,94
103,27,88
104,19,72
105,42,91


In [56]:
df.loc[
    101:104,
    ["group","score"]
]

,group,score
id,,
101,A,81
102,B,94
103,A,88
104,B,72


Part 10

In [58]:
condition = df["score"] > 80

In [59]:
condition
type(condition)

pandas.Series

In [60]:
df.loc[condition]

,age,group,score
id,,,
101,24,A,81
102,31,B,94
103,27,A,88
105,42,A,91
106,35,B,85


True or false would indicate whether that entry has a score above 80.

Part 11

In [61]:
df.loc[df["score"] > 80]

,age,group,score
id,,,
101,24,A,81
102,31,B,94
103,27,A,88
105,42,A,91
106,35,B,85


In [62]:
df.loc[df["age"] >= 30]

,age,group,score
id,,,
102,31,B,94
105,42,A,91
106,35,B,85


In [63]:
df.loc[df["group"] == "A"]

,age,group,score
id,,,
101,24,A,81
103,27,A,88
105,42,A,91


In [67]:
df

,age,group,score
id,,,
101,24,A,81
102,31,B,94
103,27,A,88
104,19,B,72
105,42,A,91
106,35,B,85


Part 12

In [71]:
df.loc[
    (df["age"] < 30) &
    (df["score"] > 80)
]

,age,group,score
id,,,
101,24,A,81
103,27,A,88


In [72]:
df.loc[
    (df["age"]>= 30) &
    (df["score"]>=85)
]

,age,group,score
id,,,
102,31,B,94
105,42,A,91
106,35,B,85


In [75]:
df

,age,group,score
id,,,
101,24,A,81
102,31,B,94
103,27,A,88
104,19,B,72
105,42,A,91
106,35,B,85


id 105 is above 90 and in group A

In [74]:
df.loc[
    (df["group"] == "A") &
    (df["score"] >= 90)
]

,age,group,score
id,,,
105,42,A,91


They match!

Part 14

In [76]:
df.loc[
    df["score"] >= 85,
    ["age", "group", "score"]
]

,age,group,score
id,,,
102,31,B,94
103,27,A,88
105,42,A,91
106,35,B,85


In [77]:
df.loc[
    df["age"] >= 30,
    ["group","score"]
]

,group,score
id,,
102,B,94
105,A,91
106,B,85


Part 15

In [78]:
df2 = pd.DataFrame(
    {
        "id": range(201, 209),
        "group": ["A", "B", "C", "A", "C", "B", "A", "C"],
        "score": [81, 94, 88, 72, 91, 85, 79, 96]
    }
).set_index("id")

In [79]:
df2.loc[
    df2["group"].isin(["A", "C"])
]

,group,score
id,,
201,A,81
203,C,88
204,A,72
205,C,91
207,A,79
208,C,96


In [85]:
df2.loc[df2["score"]>=85]

,group,score
id,,
202,B,94
203,C,88
205,C,91
206,B,85
208,C,96


In [93]:
df2.loc[
    (df2["score"]>=85) &
    (df2["group"].isin(["B","C"]))
]

,group,score
id,,
202,B,94
203,C,88
205,C,91
206,B,85
208,C,96


Part 16

In [94]:
missing_df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "age": [21, 32, None, 45, 28],
        "score": [81, None, 77, 92, 88]
    }
).set_index("id")

In [98]:
#missing_df
#missing_df.isna()
missing_df.isna().sum()

age      1
score    1
dtype: int64

In [99]:
missing_df.loc[
    missing_df["score"].isna()
]

,age,score
id,,
2,32.0,NaN


In [100]:
missing_df.loc[
    missing_df["score"].notna()
]

,age,score
id,,
1,21.0,81.0
3,NaN,77.0
4,45.0,92.0
5,28.0,88.0


A score could be recorded as the value 0, and that is very different to if the score is missing. 

Part 17

In [101]:
df["performance"] = "medium"

In [102]:
df.loc[
    df["score"] >= 90,
    "performance"
] = "high"

In [103]:
df.loc[
    df["score"] < 80,
    "performance"
] = "low"

In [104]:
df

,age,group,score,performance
id,,,,
101,24,A,81,medium
102,31,B,94,high
103,27,A,88,medium
104,19,B,72,low
105,42,A,91,high
106,35,B,85,medium


In [ ]:
df["age_group"] = "ageGroup"

In [106]:
df.loc[
    df["age"] < 30,
    "age_group"
]= "young"

In [107]:
df.loc[
    df["age"] >= 30,
    "age_group"
]= "older"

In [108]:
df

,age,group,score,performance,age_group
id,,,,,
101,24,A,81,medium,young
102,31,B,94,high,older
103,27,A,88,medium,young
104,19,B,72,low,young
105,42,A,91,high,older
106,35,B,85,medium,older


Part 18

In [ ]:
df[df["score"] > 80]["score"] = 100

In [ ]:
df.loc[
    df["score"] > 80,
    "score"
] = 100

Why do we use the .loc instead of the first option?
-> The .loc option is clearer as it ensures that we are directly changing the data frame.

Part 19

In [110]:
analysis = df.loc[
    (df["age"]>= 18) &
    (df["group"] == "A") &
    (df["score"].notna())

]
analysis

,age,group,score,performance,age_group
id,,,,,
101,24,A,81,medium,young
103,27,A,88,medium,young
105,42,A,91,high,older


Part 20

Define

Age criterion: age_group == older

Score criterion: high performing => performance == high

Missing-data criterion: score = notna

Variables required: scores, age_group, performanc

In [115]:
eligible = (
    (df["age_group"]=="older") &
    (df["performance"] == "high" )&
    (df["score"].notna())
)


eligible_df = df.loc[
    eligible,
    ["age","group","score"]
]
eligible_df

,age,group,score
id,,,
102,31,B,94
105,42,A,91


Part 21: Mini analysis challenge

In [116]:
participants = pd.DataFrame(
    {
        "id": range(1001, 1011),
        "age": [22, 34, 29, 41, 19, 37, 26, 45, 31, 28],
        "group": ["A", "B", "A", "C", "B", "A", "C", "B", "A", "C"],
        "score": [78, 91, 85, 88, 72, 95, 81, 67, 90, 84]
    }
).set_index("id")

In [ ]:
# aged 30 and older
over_thirty = participants.loc[
(participants["age"]>= 30)
]
over_thirty

,age,group,score
id,,,
1002,34,B,91
1004,41,C,88
1006,37,A,95
1008,45,B,67
1009,31,A,90


In [124]:
# Groups A or C
groupAorC = participants.loc[
    (participants["group"] == "A") |
    (participants["group"] == "C")
]
groupAorC

,age,group,score
id,,,
1001,22,A,78
1003,29,A,85
1004,41,C,88
1006,37,A,95
1007,26,C,81
1009,31,A,90
1010,28,C,84


In [125]:
score_least_85 = participants.loc[
    (participants["score"] >= 85)
]
score_least_85

,age,group,score
id,,,
1002,34,B,91
1003,29,A,85
1004,41,C,88
1006,37,A,95
1009,31,A,90


In [126]:
thirty_least85 = participants.loc[
    (participants["age"]>= 30) &
    (participants["score"]>= 85)
]
thirty_least85

,age,group,score
id,,,
1002,34,B,91
1004,41,C,88
1006,37,A,95
1009,31,A,90


In [129]:
high_scores = (
    (participants["score"] >= 90)
)

high_score_summary = participants.loc[
    high_scores,
    ["group","score"]
]
high_score_summary

,group,score
id,,
1002,B,91
1006,A,95
1009,A,90


In [131]:
not_group_b = participants.loc[
    participants["group"] != "B" 
]
not_group_b

,age,group,score
id,,,
1001,22,A,78
1003,29,A,85
1004,41,C,88
1006,37,A,95
1007,26,C,81
1009,31,A,90
1010,28,C,84


Function Challenge

In [139]:
def select_minimum_score(
        df: pd.DataFrame,
        minimum_score: float
) -> pd.DataFrame:
    df_filtered = df.loc[df["score"]> minimum_score]
    return df_filtered

select_minimum_score(participants,80)



,age,group,score
id,,,
1002,34,B,91
1003,29,A,85
1004,41,C,88
1006,37,A,95
1007,26,C,81
1009,31,A,90
1010,28,C,84
